name: Notion RSS Import

on:
  schedule:
    - cron: '0 */12 * * *'  # Cada 2 horas
  workflow_dispatch:       # Permite ejecución manual

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: go mod tidy

      - name: Run script
        env:
          NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
          NOTION_RSS_CONTENT_DATABASE_ID: ${{ secrets.NOTION_RSS_CONTENT_DATABASE_ID }}
          NOTION_RSS_FEEDS_DATABASE_ID: ${{ secrets.NOTION_RSS_FEEDS_DATABASE_ID }}
        run: go run
